version: "3.7"  # optional since v1.27.0
services:

  grafana:
    image: grafana/grafana-enterprise
    ports:
      - '3000:3000'

  prometheus:
    image: prom/prometheus
    volumes:
      - /Users/elliottarnold/slack/Slack-Clone---MERN-Stack/prom/:/etc/prometheus/
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
        - 9090:9090


  mongo_exporter:
    image:  percona/mongodb_exporter:0.20
    command:
    -  '--mongodb.uri=mongodb://db:27017/slackchannels'
    ports:
      - '9216:9216'
#   #reactApp
  slackfrontend:
   
    build: .
    ports:
      - "888:3000"    #external:internal frontend 
    depends_on:
      - db
  nodebackend:

    build: server/
    ports: 
      - "9000:9000"    #external:internal 
    depends_on:
      - db
              
  db:
    image: mongo:latest
    
    ports:
      - "27017:27017"             


# volumes:
#     prometheus_data: {}
#     grafana_data: {}

#  mongodb_exporter --mongodb.uri=mongodb://localhost:27017/slackchannels

#  # database connection url via mongoose "mongodb://db:27017/jl";
#   # netstat -an -ptcp | grep LISTEN  check for listening ports 
#   # docker rm $(docker ps -a -q) --force  - delete all containers - free up ports for dev environment
