version: "3.7"  # optional since v1.27.0
services:
  #reactApp
  slackfrontend:
   
    build: .
    ports:
      - "888:3000"    #external:internal frontend 
    depends_on:
      - db
  nodebackend:

    build: server/
    ports: 
      - "9000:9000"    #external:internal 
    depends_on:
      - db
              
  db:
   
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=si3mshady
      - MONGO_INITDB_ROOT_PASSWORD=passwd

    ports:
      - "27017:27017"             

 # database connection url via mongoose "mongodb://db:27017/jl";
  # netstat -an -ptcp | grep LISTEN  check for listening ports 
  # docker rm $(docker ps -a -q) --force  - delete all containers - free up ports for dev environment